### ISSUE TITLE
suraj yadav

### ISSUE THREAD

**Issue by SURAJYADAV0** [jigneshbhandi09/mega_project1#10]

**Comment by SURAJYADAV0** [comment]
Title:
Implement News Scraping for NDTV World Asia Section

Description:
We need to develop a script to scrape news articles from the NDTV World Asia section and save the data to a CSV file. The following details should be included for each article:

Title: The headline of the news article.
Date: The publication date of the article.
Location: The location mentioned in the article.
URL: The link to the full news article.
Tasks:
 Create a base URL for NDTV World Asia news pages.
 Loop through multiple pages to gather news articles.
 Extract the title, date, location, and URL for each article.
 Store the extracted data in a pandas DataFrame.
 Save the DataFrame to a CSV file.
Labels:
enhancement
scraping
data collection

Additional Context:
Include any additional information that may help in implementing the task, such as the expected structure of the HTML elements being scraped.

**Comment by vishal24102002** [comment]
great job suraj
