### ISSUE TITLE
Data Extraction (Scraping) - Africa

### ISSUE THREAD

**Issue by jigneshbhandi09** [jigneshbhandi09/mega_project1#4]
Arsh Malek
* Focus on scraping news from Africa.
* Assist in error handling and data validation.

**Comment by vishal24102002** [comment]
hello arsh malek please submit your report the amount of work done as well as the work which is left to be done positively by today itself before 8 

Co-Leader ->Vishal Sharma

**Comment by ArshMalik07** [comment]
Done,please check is it ok?

**Comment by vishal24102002** [comment]
GOOD JOB please remove summary part from the african new.csv file

**Comment by ArshMalik07** [comment]
done
