### ISSUE TITLE
Data Extraction (Scraping) - South America

### ISSUE THREAD

**Issue by jigneshbhandi09** [jigneshbhandi09/mega_project1#5]
Arunkumar
* Focus on scraping news from South America.
* Ensure proper categorization of news.

**Comment by vishal24102002** [comment]
please submit your report positively by today before 8 pm 

Vishal Sharma

**Comment by vishal24102002** [comment]
please add the code to your branch as well so that we can get better results

**Comment by Arunkumar00017** [comment]
okay
