### ISSUE TITLE
Data Extraction (Scraping) - North America

### ISSUE THREAD

**Issue by jigneshbhandi09** [jigneshbhandi09/mega_project1#6]
**Shreya Sunil Badve**
* Focus on scraping news from North America.
* Implement and document the scraping scripts using BeautifulSoup or Scrapy.

**Comment by Apollo-bot35** [comment]
ok

**Comment by Apollo-bot35** [comment]
<img width="909" alt="image" src="https://github.com/jigneshbhandi09/mega_project1/assets/71018084/eeda288d-fd3c-45cf-b9a4-ab21ca51fd4c">
<img width="866" alt="image" src="https://github.com/jigneshbhandi09/mega_project1/assets/71018084/5973956b-d7c8-484a-86dc-6d03e06fbde8">
today i did scraping headline and data of news from url "https://www.bbc.com/news/us-canada"
and working on it more

**Comment by vishal24102002** [comment]
great job have you added the code to your github branch. As tomorrow is the final day of submission for the mega project so kindly add the code to the github section.

Co-Leader -> Vishal Sharma
