### ISSUE TITLE
Categorization and Tagging

### ISSUE THREAD

**Issue by jigneshbhandi09** [jigneshbhandi09/mega_project1#9]
Mujar Afiya
* Develop a system to categorize the news into specified types.
* Ensure accurate tagging of news articles.

    Rahul Bajaj
* Assist in refining the categorization system.
* Work on categorizing ambiguous news articles.

**Comment by vishal24102002** [comment]
hello guys now its time to perform you job 
most of the code as well as csv files are ready and uploaded in the branches. So you are good to go take the data required from branches and combine in a single csv file with the valid data

**Comment by raulbazaz** [comment]
Working on the code

**Comment by vishal24102002** [comment]
please collaborate with afiya so that the task can be done easier and more effectively
